apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "eduvize.fullname" . }}-s3"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eduvize.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.storage.replicas }}
  selector:
    matchLabels:
      app: "{{ include "eduvize.fullname" . }}-s3"
      {{- include "eduvize.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: "{{ include "eduvize.fullname" . }}-s3"
        {{- include "eduvize.labels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ include "eduvize.fullname" . }}"
          image: {{ .Values.storage.image }}
          ports:
            - name: http
              containerPort: {{ .Values.storage.ports.http }}
            - name: console
              containerPort: {{ .Values.storage.ports.console }}
          env:
            - name: MINIO_DEFAULT_BUCKETS
              value: "{{ .Values.storage.bucketName }}:public"
            - name: MINIO_REGION
              value: {{ .Values.storage.region }}
            {{- range .Values.storage.envSecretMap }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secret }}
                  key: {{ .key }}
            {{- end}}
          volumeMounts:
            - name: "{{ include "eduvize.fullname" . }}-s3-volume"
              mountPath: /bitnami/minio/data
      volumes:
        - name: "{{ include "eduvize.fullname" . }}-s3-volume"
          persistentVolumeClaim:
            claimName: "{{ include "eduvize.fullname" . }}-s3-pvc"