services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=eduvize
    volumes:
      - ./scripts/database/seed_dev_environment.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eduvize

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - eduvize

  s3:
    image: docker.io/bitnami/minio:2024
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DEFAULT_BUCKETS=eduvize:public
      - MINIO_REGION=us-east-1
    volumes:
      - s3_data:/bitnami/minio/data
    networks:
      - eduvize

networks:
  eduvize:
    external: true

volumes:
  postgres_data:
  s3_data:
