ingress:
  enabled: true
  hostname: eduvize.dev
  ingressClassName: public
  tls:
    enabled: true
    secretName: eduvize-tls-secret
    clusterIssuer: letsencrypt-prod

frontend:
  image: registry.crosswinds.cloud/eduvize/app:latest
  port: 8000
  replicas: 1

database:
  image: registry.crosswinds.cloud/eduvize/postgres:latest
  port: 5432
  replicas: 1
  name: eduvize
  size: 10Gi
  user: eduvize_app
  envSecretMap:
    - name: POSTGRES_PASSWORD
      secret: postgres
      key: password

storage:
  image: docker.io/bitnami/minio:2024
  ports:
    http: 9000
    console: 9001
  replicas: 1
  bucketName: eduvize
  region: us-east-1
  size: 10Gi
  envSecretMap:
    - name: MINIO_ROOT_USER
      secret: s3
      key: root-user
    - name: MINIO_ROOT_PASSWORD
      secret: s3
      key: root-password

api:
  image: registry.crosswinds.cloud/eduvize/api:latest
  port: 8000
  replicas: 1
  env:
    - name: PUBLIC_UI_URL
      value: https://eduvize.dev
    - name: PUBLIC_URL
      value: https://api.eduvize.dev/api
    - name: DASHBOARD_ENDPOINT
      value: dashboard
    - name: NOREPLY_ADDRESS
      value: no-reply@mail.eduvize.dev
    - name: AUTH_REDIRECT_URL
      value: https://eduvize.dev/auth
  envSecretMap:
    - name: AWS_ACCESS_KEY
      secret: aws
      key: access-key
    - name: AWS_SECRET_KEY
      secret: aws
      key: secret-key
    - name: S3_ACCESS_KEY
      secret: s3
      key: root-user
    - name: S3_SECRET_KEY
      secret: s3
      key: root-password
    - name: OPENAI_KEY
      secret: openai
      key: api-key
    - name: MAILGUN_API_KEY
      secret: mailgun
      key: api-key
    - name: GITHUB_CLIENT_ID
      secret: github-oauth
      key: client-id
    - name: GITHUB_CLIENT_SECRET
      secret: github-oauth
      key: client-secret
    - name: GOOGLE_CLIENT_ID
      secret: google-oauth
      key: client-id
    - name: GOOGLE_CLIENT_SECRET
      secret: google-oauth
      key: client-secret

course_generator:
  image: registry.crosswinds.cloud/eduvize/course-generator:latest
  replicas: 1
  envSecretMap:
    - name: OPENAI_KEY
      secret: openai
      key: api-key

playground:
  controllerImage: registry.crosswinds.cloud/eduvize/playground-controller:latest
  environmentImagePrefix: registry.crosswinds.cloud/eduvize/playground-environment
  orchestratorImage: registry.crosswinds.cloud/eduvize/playground-orchestrator:latest

kafka:
    bootstrapServers: kafka:9092

redis:
  image: redis:6
  port: 6379
  replicas: 1

persistence:
  storageClass: microk8s-hostpath

bearerAuth:
  users:
    secret: bearer-auth
    key: signing-key
  playground:
    secret: playground-bearer-auth
    key: signing-key

privateRegistry:
  enabled: true
  secretName: regcred