name: Exercise Generator - Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/backend/jobs/exercise_generator/**"
      - "kubernetes/eduvize/templates/deployments/exercise-generator-*.yaml"

jobs:
  build-push-exercise-generator:
    name: Build and Push Course Generator Image
    uses: ./.github/workflows/reusable_build_push.yml
    with:
      IMAGE_NAME: "exercise-generator"
      DOCKERFILE: "src/backend/jobs/Dockerfile"
      BUILD_CONTEXT: "src/backend"
      BUILD_ARGS: "JOB_NAME=exercise_generator"
    secrets: inherit

  deploy-exercise-generator:
    name: Deploy Course Generator
    uses: ./.github/workflows/reusable_helm_deploy.yml
    with:
      DEPLOYMENT_NAME: "eduvize-exercise-generator"
      DOMAIN_NAME: "eduvize.ai"
    secrets: inherit
    needs: build-push-exercise-generator
