name: Frontend - Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/client/**"
      - "kubernetes/eduvize/templates/deployments/app-*.yaml"
      - "kubernetes/eduvize/templates/ingress/app-*.yaml"
      - "kubernetes/eduvize/templates/services/app-*.yaml"

jobs:
  build-push-client:
    name: Build and Push Client Image
    uses: ./.github/workflows/reusable_build_push.yml
    with:
      IMAGE_NAME: "app"
      DOCKERFILE: "src/client/Dockerfile"
      BUILD_CONTEXT: "src/client"
      BUILD_ARGS: "MODE=prod"
      ENVIRONMENT_FILE_PATH: "src/client/.env.prod"
    secrets: inherit

  deploy-client:
    name: Deploy Client
    uses: ./.github/workflows/reusable_helm_deploy.yml
    with:
      IMAGE_NAME: "app"
      IMAGE_VALUES_PATH: "frontend.image"
      DEPLOYMENT_NAME: "eduvize"
      DOMAIN_NAME: "eduvize.dev"
    secrets: inherit
    needs: build-push-client
