name: Course Generator - Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/backend/**"
      - "kubernetes/eduvize/templates/deployments/course-generation-*.yaml"

jobs:
  build-push-course-generator:
    name: Build and Push Course Generator Image
    uses: ./.github/workflows/reusable_build_push.yml
    with:
      IMAGE_NAME: "course-generator"
      DOCKERFILE: "src/backend/jobs/Dockerfile"
      BUILD_CONTEXT: "src/backend"
      BUILD_ARGS: "JOB_NAME=course_generator"
    secrets: inherit

  deploy-course-generator:
    name: Deploy Course Generator
    uses: ./.github/workflows/reusable_helm_deploy.yml
    with:
      IMAGE_NAME: "course-generator"
      IMAGE_VALUES_PATH: "course_generator.image"
      DEPLOYMENT_NAME: "eduvize-course-generator"
      DOMAIN_NAME: "eduvize.dev"
    secrets: inherit
    needs: build-push-course-generator
