name: API - Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/backend/**"
      - "kubernetes/eduvize/templates/deployments/api-*.yaml"
      - "kubernetes/eduvize/templates/ingress/api-*.yaml"
      - "kubernetes/eduvize/templates/services/api-*.yaml"

jobs:
  build-push-api:
    name: Build and Push API Image
    uses: ./.github/workflows/reusable_build_push.yml
    with:
      IMAGE_NAME: "api"
      DOCKERFILE: "src/backend/api.Dockerfile"
      BUILD_CONTEXT: "src/backend"
    secrets: inherit

  deploy-api:
    name: Deploy API
    uses: ./.github/workflows/reusable_helm_deploy.yml
    with:
      DEPLOYMENT_NAME: "eduvize-api"
      DOMAIN_NAME: "eduvize.dev"
    secrets: inherit
    needs: build-push-api
