name: Frontend - Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/client/**"
      - "kubernetes/eduvize/templates/deployments/app-*.yaml"
      - "kubernetes/eduvize/templates/ingress/app-*.yaml"
      - "kubernetes/eduvize/templates/services/app-*.yaml"

jobs:
  write-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Write Environment File
        run: |
          mkdir -p src/client
          echo "${{ secrets.CLIENT_ENVIRONMENT }}" > src/client/.env.prod

  deploy-client:
    uses: ./.github/workflows/reusable_build_deploy.yml
    with:
      IMAGE_NAME: "app"
      DOCKERFILE: "src/client/Dockerfile"
      BUILD_CONTEXT: "src/client"
      BUILD_ARGS: "MODE=prod"
    secrets: inherit
