name: Reusable Build and Deploy

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        type: string
        description: "The name of the image"
        required: true
      DOCKERFILE:
        type: string
        description: "Path to the Dockerfile"
        required: true
      BUILD_CONTEXT:
        type: string
        description: "The build context for Docker"
        required: true
      BUILD_ARGS:
        type: string
        description: "The build arguments for Docker"
        required: false
        default: ""
      REGISTRY_PREFIX:
        type: string
        description: "The registry prefix"
        required: false
        default: "eduvize"
      ENVIRONMENT_FILE_PATH:
        type: string
        description: "Path to the environment file"
        required: false
        default: ""
      RUN_TESTS:
        type: boolean
        description: "Run unit tests"
        required: false
        default: false
      PUBLISH_TEST_RESULTS:
        type: boolean
        description: "Publish test results"
        required: false
        default: false
    secrets:
      REGISTRY_NAME:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      CLIENT_ENVIRONMENT:
        required: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Write Environment File
        if: ${{ inputs.ENVIRONMENT_FILE_PATH }}
        run: |
          echo "${{ secrets.CLIENT_ENVIRONMENT }}" > ${{ inputs.ENVIRONMENT_FILE_PATH }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug Docker Registry Info
        run: |
          echo "Registry Name: ${{ secrets.REGISTRY_NAME }}"

      - name: Log in to Private Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login "${{ secrets.REGISTRY_NAME }}" -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and Push Image
        run: |
          if [ ${{ inputs.RUN_TESTS }} = true ]; then
            TAG="test-${{ github.sha}}"
          else
            TAG="${{ github.sha }}"
          fi

          if [ -n "${{ inputs.REGISTRY_PREFIX }}" ]; then
            IMAGE_REPO="${{ inputs.REGISTRY_PREFIX }}/${{ inputs.IMAGE_NAME }}:${TAG}"
          else
            IMAGE_REPO="${{ inputs.IMAGE_NAME }}:${TAG}"
          fi
            
          # Build Args
          if [ -n "${{ inputs.BUILD_ARGS }}" ]; then
            BUILD_ARGS_STR="--build-arg ${{ inputs.BUILD_ARGS }}"
          else
            BUILD_ARGS_STR=""
          fi

          # Testing environment variable
          if [ ${{ inputs.RUN_TESTS }} = true ]; then
            ADDITIONAL_ARGS_STR="--build-arg RUN_TESTS=1"
          else
            ADDITIONAL_ARGS_STR=""
          fi
            
          echo "Building ${{ secrets.REGISTRY_NAME }}/${IMAGE_REPO}"
          docker build $BUILD_ARGS_STR $ADDITIONAL_ARGS_STR -f ${{ inputs.DOCKERFILE }} -t ${{ secrets.REGISTRY_NAME }}/${IMAGE_REPO} ${{ inputs.BUILD_CONTEXT }}
          docker push ${{ secrets.REGISTRY_NAME }}/${IMAGE_REPO}
      - name: Retrieve Test Results
        if: ${{ inputs.RUN_TESTS && inputs.PUBLISH_TEST_RESULTS }}
        run: |
          if [ -n "${{ inputs.REGISTRY_PREFIX }}" ]; then
            IMAGE_REPO="${{ inputs.REGISTRY_PREFIX }}/${{ inputs.IMAGE_NAME }}:test-${{ github.sha }}"
          else
            IMAGE_REPO="${{ inputs.IMAGE_NAME }}:test-${{ github.sha }}"
          fi

          docker create --name test-container ${{ secrets.REGISTRY_NAME }}/${IMAGE_REPO}

      - name: Copy Test Results from Container
        if: ${{ inputs.RUN_TESTS && inputs.PUBLISH_TEST_RESULTS }}
        run: |
          docker cp test-container:/app/test-results.xml test-results.xml

      - name: Upload Test Results
        if: ${{ inputs.RUN_TESTS && inputs.PUBLISH_TEST_RESULTS }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml

      - name: Clean up Test Container
        if: ${{ inputs.RUN_TESTS && inputs.PUBLISH_TEST_RESULTS }}
        run: |
          docker rm test-container
