name: API - Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "src/backend/**"

jobs:
  build-push-api:
    name: Build and Test API Image
    uses: ./.github/workflows/reusable_build_push.yml
    with:
      IMAGE_NAME: "api"
      DOCKERFILE: "src/backend/api.Dockerfile"
      BUILD_CONTEXT: "src/backend"
      RUN_TESTS: true
      PUBLISH_TEST_RESULTS: true
      SHOULD_PUSH_IMAGE: false
    secrets: inherit

  comment-on-failure:
    name: Comment on PR if tests fail
    needs: build-push-api
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Post failure comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ The API build and test job failed. Please check the logs for more details.'
            })
