name: Playground Orchestrator - Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "src/playground-orchestrator/**"

jobs:
  build-push-api:
    name: Build and Test Playground Orchestrator Image
    uses: ./.github/workflows/reusable_build_push.yml
    with:
      IMAGE_NAME: "playground-orchestrator"
      DOCKERFILE: "src/playground-orchestrator/Dockerfile"
      BUILD_CONTEXT: "src/playground-orchestrator"
      RUN_TESTS: true
    secrets: inherit
