name: Playground Orchestrator - Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "src/playground-orchestrator/**"

jobs:
  build-push-playground-orchestrator:
    name: Build and Test Playground Orchestrator Image
    uses: ./.github/workflows/reusable_build_push.yml
    with:
      IMAGE_NAME: "playground-orchestrator"
      DOCKERFILE: "src/playground-orchestrator/Dockerfile"
      BUILD_CONTEXT: "src/playground-orchestrator"
      RUN_TESTS: true
      SHOULD_PUSH_IMAGE: false
    secrets: inherit

  comment-on-failure:
    name: Comment on PR if tests fail
    needs: build-push-playground-orchestrator
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Post failure comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ The Playground Orchestrator build and test job failed. Please check the logs for more details.'
            })
